version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          - RAILS_ENV: test
          - BUNDLE_JOBS: 4
          - BUNDLE_RETRY: 3
          - BUNDLE_PATH: vendor/bundle
      
jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  checkout_code2:
    executor: default
    steps:
      - checkout

  checkout_code_else:
    executor: default
    steps:
      - checkout

  bundle_install:
    executor: default
    steps:
      - checkout
      - run:
          name: Download CC test reporter
          command: |
            mkdir -p ./tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run: gem install bundler
      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - save_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - /vendor/bundle
      - persist_to_workspace:
          root: ~/repo
          paths:
            - vendor/bundle
            - tmp

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - bundle_install:
          requires:
            - checkout_code            
      - checkout_code_else:
          requires:
            - checkout_code
